### Numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)
print(arr2.shape)
arr2.reshape(4,2)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr=np.array([[1,2,3,4],[2,3,4,5]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("Data type",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3 4]
 [2 3 4 5]]
Shape: (2, 4)
number of dimensions: 2
Data type int64
Item size (in bytes): 8


In [18]:
### Numpy Vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,9,8,7,6])

## Element wise addition
print("Addition",arr1+arr2)

## Element wise subtraction
print("Subtraction",arr1-arr2)

## Element wise multiplication
print("multiplication",arr1*arr2)

## Element wise Division
print("Division",arr1/arr2)

Addition [11 11 11 11 11]
Subtraction [-9 -7 -5 -3 -1]
multiplication [10 18 24 28 30]
Division [0.1        0.22222222 0.375      0.57142857 0.83333333]


In [23]:
### Universal Function
arr=np.array([1,2,3,4,5])

##square root
print(np.sqrt(arr))

## Exponentiol
print(np.exp(arr))

## sine
print(np.sin(arr))

## log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
## array slicing and indexing

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]])
print("array:\n",arr)

array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [ ]:
print(arr[0][3])
print(arr[0][2:])
print(arr[1:])
print(arr[1:,2:])
print(arr[0:2,3:])
print(arr[1:,3:])


4
[3 4 5]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 8  9 10]
 [ 3  4  5]]
[[ 4  5]
 [ 9 10]]
[[ 9 10]
 [ 4  5]]


In [41]:
arr[0,1]=23
arr[2,1]=100
arr[1:]=100
print(arr)

[[  1  23   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [42]:
## statistical concept-Normalization
## to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

## calculate mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

## Normalize the data
normalized_data= (data-mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print("Mean:",mean)

median=np.median(data)
print("Median:",median)

std_dev=np.std(data)
print("standard deviation:",std_dev)

variance=np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
standard deviation: 2.8722813232690143
Variance: 8.25


In [48]:
## Logical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<9)]

array([6, 7, 8])

In [2]:


# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[ 8 13 16 13 15]
 [16  7 16  7  3]
 [19 20  5 20  8]
 [ 2 13  9  7 16]
 [13  1  2  6  5]]
Modified array:
[[ 8 13  1 13 15]
 [16  7  1  7  3]
 [19 20  1 20  8]
 [ 2 13  1  7 16]
 [13  1  1  6  5]]


In [3]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


In [4]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[ 7 10  8]
 [10  7  2]
 [ 5  4  7]]
1D array:
[ 8  3 10]
Resulting array:
[[15 13 18]
 [18 10 12]
 [13  7 17]]


In [5]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 9 10  5  9]
 [10  3  9  4]
 [10  9 10 10]
 [ 1  2  1  1]]
1D array:
[8 4 1 6]
Resulting array:
[[ 1  2 -3  1]
 [ 6 -1  5  0]
 [ 9  8  9  9]
 [-5 -4 -5 -5]]


In [6]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[17  1 19  1 10]
 [ 8  3  8 13  6]
 [20  9 16 17  5]
 [19 12 17 20 13]
 [19  4 18  6  3]]
Flattened array:
[17  1 19  1 10  8  3  8 13  6 20  9 16 17  5 19 12 17 20 13 19  4 18  6
  3]
Reshaped array:
[[17  1 19  1 10]
 [ 8  3  8 13  6]
 [20  9 16 17  5]
 [19 12 17 20 13]
 [19  4 18  6  3]]


In [7]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
